<h1>Python: without numpy or sklearn </h1>

<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [23 30 36 42 51]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

In [2]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples


# you can free to change all these codes/structure
# here A and B are list of lists
def matrix_mul(A, B):
    
    n1 , m1 = len(A) , len(A[0])
    n2 , m2 = len(B) , len(B[0])

    if m1 !=n2:
        assert "Dimension mismatch"

    result = [ [0]*m2 for i in range(n1) ]

    for i in range(n1):
        for j in range(m2):
            sum_vertices = 0 
            for k in range(m1):
                sum_vertices += A[i][k] * B[k][j]
            result[i][j] = sum_vertices



    return  result #multiplication_of_A_and_B)

A   =  [[1 ,3 , 4],
        [2 ,5, 7],
        [5, 9 ,6]]

B   =  [[1 , 0 ,0],
        [0, 1, 0],
        [0, 0, 1]]

matrix_mul(A, B) 

[[1, 3, 4], [2, 5, 7], [5, 9, 6]]

<h3> Q2: Select a number randomly with probability proportional to its magnitude from the given array of n elements</h3>

consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

In [1]:
from random import uniform
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples


# you can free to change all these codes/structure
def pick_a_number_from_list(A):
    sum_all = sum(A)
    cum_sum = [0]* len(A)
    cum_sum[0] = A[0]
    for i in range(1,len(A)):
        cum_sum[i] = A[i] + cum_sum[i-1]
    cum_sum = list(map(lambda x: x/cum_sum[-1] , cum_sum))
    random_number = uniform(0 , 1)
    for i in range(len(cum_sum)):
        if random_number < cum_sum[i]:
            return A[i]
    return #selected_random_number

def sampling_based_on_magnitued():
    A = [ 0 , 5, 27, 6 , 13 , 28 , 100 , 45 , 10 , 79]
    selection = []
    for i in range(1,500):
        number = pick_a_number_from_list(A)
        selection.append(number)
    
    count = {}
    for i in selection:
        if i in count.keys():
            count[i]+=1
        else:
            count[i] = 0
    print(count)

sampling_based_on_magnitued()

{28: 36, 79: 130, 27: 44, 45: 66, 100: 159, 10: 17, 6: 10, 13: 24, 5: 4}


<h3> Q3: Replace the digits in the string with #</h3>

consider a string that will have digits in that, we need to remove all the not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [38]:
import re
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

# you can free to change all these codes/structure
# String: it will be the input to your program
def replace_digits(String):
    # write your code
    numbers = re.findall(r"\d+" , String)
    result = ""
    for i in numbers:
        result+= "#"*len(i)

    return result# modified string which is after replacing the # with digits

String="abc"
replace_digits(String)

''

<h3> Q4: Students marks dashboard</h3>

consider the marks list of class students given two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 35, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on <br><br>
your task is to print the name of students
<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks</strong>

<pre>
Ex 1: 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]
a. 
student8  98
student10 80
student2  78
student5  48
student7  47
b.
student3 12
student4 14
student9 35
student6 43
student1 45
c.
student9 35
student6 43
student1 45
student7 47
student5 48
</pre>

In [3]:
import math
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

# you can free to change all these codes/structure
def display_dash_board(students, marks):
    
    mapping = {}
    for i in range(len(marks)):
        mapping[marks[i]] = students[i]
    
    marks.sort(reverse=True)
    
    top_5_marks = marks[:5]
    top_5_students = [mapping[i] for i in top_5_marks]
    # write code for computing top least 5 students
    least_5_marks = marks[::-1][:5]
    least_5_students = [mapping[i] for i in least_5_marks]
    # write code for computing top least 5 students
    percentile_25 = math.ceil(0.25 * len(marks))
    percentile_75 = math.ceil(0.75 * len(marks))
    between_marks = marks[percentile_25:percentile_75]
    students_within_25_and_75 = [mapping[i] for i in between_marks]
    
    return top_5_students, least_5_students, students_within_25_and_75

students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]

top_5_students, least_5_students, students_within_25_and_75 = display_dash_board(students, marks)
print(top_5_students)# those values)
print(least_5_students)
print(students_within_25_and_75)

['student8', 'student10', 'student2', 'student5', 'student7']
['student3', 'student4', 'student9', 'student6', 'student1']
['student5', 'student7', 'student1', 'student6', 'student9']


<h3> Q5: Find the closest points</h3>

consider you have given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> your task is to find 5 closest points(based on cosine distance) in S from P
<br>cosine distance between two points (x,y) and (p,q) is defind as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1)(6,0),(1,-1)]
P= (3,-4)
<img src='https://i.imgur.com/vIFPOcG.jpg', width=300>
Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>

In [10]:
import math

# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
# you can free to change all these codes/structure


def cosine_distance(x , y):
    term = x[0] * y[0] + x[1] * y[1]
    term1 = math.sqrt(x[0]**2 + x[1]**2)
    term2 = math.sqrt(y[0]**2 + y[1]**2)

    return math.acos(term / (term1 * term2))



# here S is list of tuples and P is a tuple ot len=2
def closest_points_to_p(S, P):
    distances = []
    for i in S:
        distances.append(cosine_distance(i , P))
    
    mapping = {}
    for i in range(len(distances)):
        if distances[i] in mapping.keys():
            mapping[distances[i]].append(S[i])
        else:
            mapping[distances[i]] = [S[i]]
    
    distances.sort()

    result = []
    for i in distances:
        for j in mapping[i]:
            result.append(j)
        

    return result[:5]  # its list of tuples

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1),(6,0),(1,-1)]
P= (3,-4)
points = closest_points_to_p(S, P)
print(points) #print the returned values

[(6, -7), (1, -1), (6, 0), (-5, -8), (-1, -1)]


<h3> Q6: Find Which line separates oranges and apples</h3>
consider you have given two set of data points in the form of list of tuples like 
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string formate, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: you need to string parsing here and get the coefficients of x,y and intercept
</pre>
your task is to for each line that is given print "YES"/"NO", you will print yes, if all the red points are one side of the line and blue points are other side of the line, otherwise no
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/DoQf7mE.jpg' width=400>
Output:
YES
NO
NO
YES
</pre>

In [17]:
import math
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


# you can free to change all these codes/structure
def i_am_the_one(red,blue,line):
    red_sep = []
    blue_sep = []
    line = line.replace("-" , '+-')
    coeffs = line.split("+")
    a = float(coeffs[0].replace("x",""))
    b = float(coeffs[1].replace("y",""))
    c = float(coeffs[2])

    for i in red:
        distance = i[0]*a + i[1]*b + c
        red_sep.append(1 if distance > 0 else -1)
    
    for i in blue:
        distance = i[0]*a + i[1]*b + c
        blue_sep.append(1 if distance > 0 else -1)
    
    decision = "yes"
    for i in range(1, len(red_sep)):
        if red_sep[i] * red_sep[i-1] != 1:
            return "no"
    
    for i in range(1, len(blue_sep)):
        if blue_sep[i] * blue_sep[i-1] != 1:
            return "no"
    
    return "yes"

Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]

for i in Lines:
    yes_or_no = i_am_the_one(Red, Blue, i)
    print(yes_or_no) # the returned value

yes
no
no
yes


<h3> Q7: Filling the missing values in the specified formate</h3>
You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 
<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4
</pre>



In [34]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


# you can free to change all these codes/structure
def curve_smoothing(string):
    l = string.split(",")
    if l[0] != "_":
        start = int(l[0])
    else:
        start = 0 
    idx = 0

    for i in range(1, len(l)):
        if l[i] != "_"  :
            
            value = int(l[i])
            average = (start + value ) / (i - idx+1)
          
            for j in range(idx , i+1):
                l[j] = average
            start = average
            idx = i 
        elif i == len(l)-1:
            value = 0 
            average = (start + value ) / (i - idx+1)
          
            for j in range(idx , i+1):
                l[j] = average
            start = average
            idx = i 

    return l

S=  "_,_,30,_,_,_,50,_,_"
smoothed_values= curve_smoothing(S)
print(smoothed_values)# print above values)

[10.0, 10.0, 12.0, 12.0, 12.0, 12.0, 4.0, 4.0, 4.0]


<h3> Q8: Filling the missing values in the specified formate</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns
1. the first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
2. the second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>
Ex:

<pre>
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3
</pre>




In [41]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings

def compute_probabilites(F , S , A):
    filtered = [ [x , y] for x , y in A if y == S  ]
    demon = len(filtered)
    filtered_num = [ [x , y] for x , y in filtered if x == F ]
    numerator = len(filtered_num)

    return str(numerator)+"/"+str(demon)

# you can free to change all these codes/structure
def compute_conditional_probabilites(A):
    l1 = ["F1" , "F2" , "F3" , "F4" , "F5" ]
    l2 = ["S1" , "S2" , "S3"]

    for i in l1:
        for j in l2:
            print(f"P({i}/{j}) = {compute_probabilites(i , j , A)}  " , end="")
        print()

A = [['F1','S1'],['F2','S2'],['F3','S3'],['F1','S2'],['F2','S3'],['F3','S2'],['F2','S1'],['F4','S1'],['F4','S3'],['F5','S1']]

compute_conditional_probabilites(A)

P(F1/S1) = 1/4  P(F1/S2) = 1/3  P(F1/S3) = 0/3  
P(F2/S1) = 1/4  P(F2/S2) = 1/3  P(F2/S3) = 1/3  
P(F3/S1) = 0/4  P(F3/S2) = 1/3  P(F3/S3) = 1/3  
P(F4/S1) = 1/4  P(F4/S2) = 0/3  P(F4/S3) = 1/3  
P(F5/S1) = 1/4  P(F5/S2) = 0/3  P(F5/S3) = 0/3  


<h3> Q9: Given two sentances S1, S2</h3>
You will be given two sentances S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [47]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings

# you can free to change all these codes/structure
def string_features(S1, S2):
    
    l1 = S1.split(" ")
    l2 = S2.split(" ")

    s1 = set(l1)
    s2 = set(l2)

    a = len(s1.intersection(s2))
    b = s1.difference(s2)
    c = s2.difference(s1)

    return a, b, c

S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
a,b,c = string_features(S1, S2)
print(a,b,c )#the above values)

7 {'first', '5', 'F'} {'S', 'second', '3'}


<h3> Q10: Given two sentances S1, S2</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.4243099
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

In [56]:
import math
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


# you can free to change all these codes/structure
def compute_log_loss(A):
    sum_all = 0 
    for i , j in A:
        if i ==1:
            sum_all += i* math.log10(j)
        else:
            sum_all += math.log10(1-j)
    
    loss = -1* sum_all/(len(A))
    
    return loss

A = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
loss = compute_log_loss(A)
print(loss)# the above loss)

0.42430993457031635
